### ISSUE TITLE
Base mixerapi tries to load Search plugin

### ISSUE THREAD

**Issue by segy** [mixerapi/mixerapi#2]
Base mixerapi tries to load the Search plugin. This is only recommended and is not required in composer.json, so if you install only mixerapi, you get a MissingPluginException.

**Comment by cnizzardini** [comment]
What version are you using?

**Comment by cnizzardini** [comment]
This has been resolved in https://github.com/mixerapi/mixerapi/releases/tag/v1.1.4 if you are using v0.* you may open a new issue.
