### ISSUE TITLE
Deprecation warning for PHP 8.1: Upgrade php-dot-notation dependency to ^2.3

### ISSUE THREAD

**Issue by jamisonbryant** [mixerapi/mixerapi#3]
I noticed this blob at the top of my documentation after upgrading to PHP 8.1:
> [Deprecated (8192) ](javascript:void(0);): Return type of Adbar\Dot::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [in /shared/httpd/ticketsauce-api/vendor/adbario/php-dot-notation/src/Dot.php, line 603]
[Warning (512) ](javascript:void(0);): Unable to emit headers. Headers sent in file=/shared/httpd/ticketsauce-api/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php line=36 [in /shared/httpd/ticketsauce-api/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 71]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /shared/httpd/ticketsauce-api/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:36) [in /shared/httpd/ticketsauce-api/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 168]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /shared/httpd/ticketsauce-api/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:36) [in /shared/httpd/ticketsauce-api/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 197]

Digging into the dependencies, I found that `mixerapi/collection-view` has a dependency on v2.2 of the `adbario/php-dot-notation` package. [This deprecation issue has been fixed in v2.3 of the package](https://github.com/adbario/php-dot-notation/issues/33). 

Could the maintainers of `mixerapi/collection-view` please evaluate whether an upgrade to v2.3 is appropriate so the deprecation error goes away? It would be much appreciated.

**Comment by jamisonbryant** [comment]
Apologies if this is the wrong forum for this issue, it looked to me like all MixerAPI repos roll up to this one and collection-view had 0 closed issues, 0 actives.

**Comment by cnizzardini** [comment]
> Apologies if this is the wrong forum for this issue, it looked to me like all MixerAPI repos roll up to this one and collection-view had 0 closed issues, 0 actives.

No problem, thanks for the report.

**Comment by cnizzardini** [comment]
@jamisonbryant looks harmless to bump up the default version so that shouldn't be a problem. As a workaround for right now did you try `composer update -W`?

**Comment by jamisonbryant** [comment]
I did, it says I have nothing to install, update, or remove. I'm not using `collection-view` directly, I had to go hunting down the tree to find the deprecation error. Here are my dependencies:

```
"require": {
    "php": ">=8.1",
    "ext-intl": "*",
    "ext-json": "*",
    "ext-mbstring": "*",
    "ext-mysqli": "*",
    "ext-pdo_mysql": "*",
    "ext-simplexml": "*",
    "cakephp/cakephp": "~4.4",
    "cakephp/migrations": "^3.2",
    "cakephp/plugin-installer": "^1.3",
    "cnizzardini/cakephp-swagger-bake": "^2.4",
    "mixerapi/bake": "^1.1",
    "mixerapi/crud": "^1.1",
    "mixerapi/mixerapi": "^1.1",
    "mixerapi/rest": "^1.1",
    "mobiledetect/mobiledetectlib": "^2.8"
},
```

**Comment by cnizzardini** [comment]
Weird maybe its `composer update mixerapi/mixerapi -W`

**Comment by cnizzardini** [comment]
By requiring mixerapi/mixerapi you automatically get: cnizzardini/cakephp-swagger-bake, mixerapi/bake, and mixerapi/rest 

The only one of those packages not included with mixerapi/mixerapi is mixerapi/crud.

**Comment by jamisonbryant** [comment]
> Weird maybe its composer update mixerapi/mixerapi -W

I tried that, and also `composer update mixerapi/collection-view -W`. I'm not sure what the problem is. In any case, the deprecation is a minor annoyance not a showstopper, however I wanted to be a good user and let you know about it.

> By requiring mixerapi/mixerapi you automatically get: cnizzardini/cakephp-swagger-bake, mixerapi/bake, and mixerapi/rest

I realize that now, I'm just now becoming fully aware of this impressive monorepo! 👍

**Comment by cnizzardini** [comment]
https://github.com/mixerapi/mixerapi/releases/tag/v1.1.5

**Comment by cnizzardini** [comment]
> I realize that now, I'm just now becoming fully aware of this impressive monorepo! +1

Yeah it can be installed kitchen sink or just want you need.

**Comment by jamisonbryant** [comment]
I apologize, it looks like the maintainer of `php-dot-notation` did NOT adequately fix the issue in 2.3 or 2.4. I will let them know and then come back to you to bump the version again if that's alright 🤦 

Sorry for the fuss, I don't know why didn't check for myself, only took the maintainer's word.

**Comment by jamisonbryant** [comment]
Final update: I put in a PR for the upstream package which corrected the issue, and the maintainer released a patch version. No further changes required for this repo.

Thanks everyone

**Comment by cnizzardini** [comment]
Np, I too went off the maintainers release notes, sometimes we mess up haha. Thanks.

**Comment by cnizzardini** [comment]
Solid work by maintainers today though, thats quick turn around across the board!

**Comment by jamisonbryant** [comment]
I know!!!! I am using this as an example of why version constraints and release automation work wonders.
