### ISSUE TITLE
how upgrade system with cakephp 5

### ISSUE THREAD

**Issue by arbims** [mixerapi/mixerapi#7]
This pluggin has many error with cakephp 5

**Comment by cnizzardini** [comment]
It's under development: https://github.com/mixerapi/mixerapi-dev/pull/141

Would you be interested in helping test if I release an RC?

**Comment by arbims** [comment]
yes i'm very intersted sorry for my english

**Comment by cnizzardini** [comment]
This is released: https://github.com/mixerapi/mixerapi/releases

Need to update some documentation and stuff still, but its now been tested in multiple applications. I would appreciate feedback.
